set(CPACK_PACKAGE_VENDOR "Matt Johnston")
set(CPACK_PACKAGE_CONTACT "Matt Johnston <matt@ucc.asn.au>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Dropbear scp executable")
set(CPACK_PACKAGE_VERSION_MAJOR 2015)
set(CPACK_PACKAGE_VERSION_MINOR 67)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(CPACK_GENERATOR "DEB")

include(CPack)
